// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	Email       string
	Password    string
	Avatar      sql.NullString
	PhoneNumber sql.NullString
	Birthday    sql.NullTime
	FullName    string
	UpdatedAt   time.Time
	CreateAt    time.Time
}
